---
# tasks file for mfts

- name: install packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=1200
  with_items:
    - "{{ mfts_packages }}"

- name: install additional packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=1200
  with_items:
    - "{{ mfts_additional_packages }}"

- name: remove packages
  apt: pkg={{ item }}
  state: absent
  with_items:
    - "{{ mfts_removal_packages }}"

- name: change locales
  locale_gen:
    name: "{{ item }}"
  with_items: 
    - "{{ mfts_locales }}"

- name: exec update-locale
  command: update-locale LANG="{{ mfts_locales[0] }}"
    
- name: modify escape for screen
  lineinfile:
    path: /etc/screenrc
    regexp: "^escape"
    line: 'escape: "^t^t"'

- name: modify hardstatus for screen
  lineinfile:
    path: /etc/screenrc
    regexp: "^hardstatus"
    line: 'hardstatus alwayslastline "%-w [screen %n%?: %t%?] %+w (%Y/%m/%d %c)"'
- name: modify shelltitle for screen
  lineinfile:
    path: /etc/screenrc
    regexp: "^shelltitle"
    line: 'shelltitle: "{{ ansible_hostname }}"'

- name: setting timezone
  timezone:
    name: "{{ mfts_timezone }}"

- name: modify dist-upgrade setting in cron-apt config file
  become: True
  lineinfile:
    path: /etc/cron-apt/action.d/3-download
    regexp: "^dist-upgrade"
    line: "dist-upgrade -y -o APT::Get::Show-Upgraded=true"
  register: result

- name: modify autoremove setting in cron-apt config file
  become: True
  lineinfile:
    path: /etc/cron-apt/action.d/3-download
    insertafter: "^autoclean"
    regexp: "^autoremove"
    line: "autoremove -y"
  register: result

- name: modify the sshd listen address
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^ListenAddress"
    line: "ListenAddress {{ mfts_sshd_listen_ipaddr }}"
  when: mfts_sshd_listen_ipaddr != ''
  register: result

- name: ssh modify the config file to disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  register: result

- name: enable ssh.service on systemd
  systemd:
    name: ssh
    state: started
    enabled: true
  register: result
